spring:
  datasource:
    url: jdbc:h2:mem:creditapp_db
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
